### ISSUE TITLE
Function arguments being evaluated once when the function is defined breaks setSyncTimeMs()

### ISSUE THREAD

**Issue by kizniche** [Mailblocker/pySmartGadget#3]
setSyncTimeMs() has a default argument ```timestamp=time.time()```, however since Python arguments are only evaluated once when the function is defined, if ```timstamp``` isn't passed to setSyncTimeMs(), the same timestamp will be used rather than a new timestamp being generated each time setSyncTimeMs() is called. Consequently, this negatively affects the ability to sync the time, and causes an inability to get the correct readNewestTimestampMs() and properly assign timestamps to data.

The function in question is:

https://github.com/Mailblocker/pySmartGadget/blob/c513d2655dd9690427dd5b76c29c493b74ebb1ab/pySmartGadget/pySmartGadget.py#L142-L144

And I have confirmed changing this to the following alleviates the issues:

```python
    def setSyncTimeMs(self, timestamp=None):
        timestampMs = timestamp if timestamp else int(round(time.time() * 1000))
        self.__characteristics['SyncTimeMs'].write(timestampMs.to_bytes(8, byteorder='little'))
```

I had found this issue the last time I was working with your module and made my last issue, but I forgot that I had made this edit at the time.

The following example code demonstrates the issue:

```python
import time

def timestamp_01(ts=time.time()):
    print(int(ts))

def timestamp_02(ts=None):
    timestamp = ts if ts else time.time()
    print(int(timestamp))

timestamp_01()
time.sleep(1)
timestamp_01()
time.sleep(1)
timestamp_01()

print('')
time.sleep(1)

timestamp_02()
time.sleep(1)
timestamp_02()
time.sleep(1)
timestamp_02()
```

The output of this is:

```
1548715442
1548715442
1548715442

1548715445
1548715446
1548715447
```

**Comment by Mailblocker** [comment]
Thanks for the explanation! I was not aware of this behaviour, fixed it just now.
